### ISSUE TITLE
IllegalAccessError on latest avro

### ISSUE THREAD

**Issue by naveencotha-zt** [allegro/json-avro-converter#39]
I am using this lib (with avro 1.8.2) on Amazon EMR, when I run on the master node this issue happens, any ideas?
```
java.lang.IllegalAccessError: tried to access method org.apache.avro.io.JsonEncoder.<init>(Lorg/apache/avro/Schema;Ljava/io/OutputStream;)V from class org.apache.avro.io.NoWrappingJsonEncoder
	at org.apache.avro.io.NoWrappingJsonEncoder.<init>(NoWrappingJsonEncoder.java:12)
	at tech.allegro.schema.json2avro.converter.JsonAvroConverter.convertToJson(JsonAvroConverter.java:93)
```

**Comment by naveencotha-zt** [comment]
I was able to fix the issue on my end, here is what I think is happening, 
`tech.allegro.schema.json2avro` has a class in package `org.apache.avro` in which the actual `apache avro` has classes, but by default avro is loaded in one of the different classloader on EMR(Amazon) (may be spark's, emr's, hadoop's) than my application class loader where this lib is loaded, and so I think this makes it inaccessible (ie like a classloader conflict)
   ```Error: java.lang.IllegalAccessError: tried to access method org.apache.avro.io.JsonEncoder.<init>(Lorg/apache/avro/Schema;Ljava/io/OutputStream;Z)V from class org.apache.avro.io.NoWrappingJsonEncoder
  at org.apache.avro.io.NoWrappingJsonEncoder.<init>(NoWrappingJsonEncoder.java:17)```
