### ISSUE TITLE
Field is expected to be type: java.util.Map

### ISSUE THREAD

**Issue by mariussoutier** [allegro/json-avro-converter#6]
When I try to convert input JSON with a schema that has some ebedded records, I get the exception `Field <fieldname> expected to be type: java.util.Map` when calling `convertToGenericDataRecord` where <fieldname> is the name of the embedded record field.

Stacktrace:

```
tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro
 at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:47)
 at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:36)
 at tech.allegro.schema.json2avro.converter.JsonAvroConverter.convertToGenericDataRecord(JsonAvroConverter.java:47)
```

**Comment by adamdubiel** [comment]
Can you provide us with a sample schema and data to reproduce this? Or can you test 0.2.4, which fixed some similar issues?

**Comment by adamdubiel** [comment]
Closing - if problems persists feel free to reopen, but please attach schema + message that can be used to reproduce the problem.
